<a href="https://colab.research.google.com/github/eirikrbe/MSE800-PSD/blob/main/W1Act5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pwd

'/content'

In [3]:
ls

drive/  sample_data/

In [4]:
cd drive/

/content/drive

In [5]:
ls

MyDrive/

In [6]:
cd MyDrive/

/content/drive/MyDrive

In [7]:
ls

'Colab Notebooks'/  'My Drive'/

In [8]:
cd Colab\ Notebooks

/content/drive/MyDrive/Colab Notebooks

In [9]:
ls

Main.ipynb  W1/

In [10]:
cd W1/

/content/drive/MyDrive/Colab Notebooks/W1

In [11]:
ls

W1Act5.ipynb

In [23]:
from google.colab import files
upload = files.upload()
print(upload.keys())

Saving dataset1.csv to dataset1.csv
dict_keys(['dataset1.csv'])

In [24]:
ls

dataset1.csv  W1Act5.ipynb

In [30]:
import pandas as pd
df = pd.read_csv('dataset1.csv')
display(df.head())
print(f"Size {df.shape}")

    41  13  18   11  54  63  37  16
0   29  20  35   71  58  46  25  46
1  100  34  73   10  48  19  47   1
2   10  69  50   16  82  32  63  38
3   38  12  11  100  36  28  94  85

Size (4, 8)

In [44]:
df = pd.read_csv('dataset1.csv', header=None)
display(df.head())
print(f"Size {df.shape}")

     0   1   2    3   4   5   6   7
0   41  13  18   11  54  63  37  16
1   29  20  35   71  58  46  25  46
2  100  34  73   10  48  19  47   1
3   10  69  50   16  82  32  63  38
4   38  12  11  100  36  28  94  85

Size (5, 8)

In [46]:
column_sum = df.sum(axis=0)
column_average = df.mean(axis=0)
row_sum = df.sum(axis=1)
row_average = df.mean(axis=1)
print(row_sum)
print(row_average)
print(column_sum)
print(column_average)

0    253
1    330
2    332
3    360
4    404
dtype: int64
0    31.625
1    41.250
2    41.500
3    45.000
4    50.500
dtype: float64
0    218
1    148
2    187
3    208
4    278
5    188
6    266
7    186
dtype: int64
0    43.6
1    29.6
2    37.4
3    41.6
4    55.6
5    37.6
6    53.2
7    37.2
dtype: float64

In [61]:
df['Row sum'] = row_sum
df['Row Average'] = row_average
display(df)

     0   1   2    3   4   5   6   7  Row sum  Row Average
0   41  13  18   11  54  63  37  16      253       31.625
1   29  20  35   71  58  46  25  46      330       41.250
2  100  34  73   10  48  19  47   1      332       41.500
3   10  69  50   16  82  32  63  38      360       45.000
4   38  12  11  100  36  28  94  85      404       50.500

In [62]:
column_sum_row = pd.DataFrame(column_sum).T
column_average_row = pd.DataFrame(column_average).T
display(column_sum_row)
display(column_average_row)

     0    1    2    3    4    5    6    7
0  218  148  187  208  278  188  266  186

      0     1     2     3     4     5     6     7
0  43.6  29.6  37.4  41.6  55.6  37.6  53.2  37.2

In [63]:
column_sum_row.index = ['Column_Sum']
column_average_row.index = ['Column_Average']
display(column_sum_row)
display(column_average_row)

              0    1    2    3    4    5    6    7
Column_Sum  218  148  187  208  278  188  266  186

                   0     1     2     3     4     5     6     7
Column_Average  43.6  29.6  37.4  41.6  55.6  37.6  53.2  37.2

In [64]:
df_final = pd.concat([df, column_sum_row, column_average_row])
display(df_final)

,0,1,2,3,4,5,6,7,Row sum,Row Average
0,41.0,13.0,18.0,11.0,54.0,63.0,37.0,16.0,253.0,31.625
1,29.0,20.0,35.0,71.0,58.0,46.0,25.0,46.0,330.0,41.250
2,100.0,34.0,73.0,10.0,48.0,19.0,47.0,1.0,332.0,41.500
3,10.0,69.0,50.0,16.0,82.0,32.0,63.0,38.0,360.0,45.000
4,38.0,12.0,11.0,100.0,36.0,28.0,94.0,85.0,404.0,50.500
Column_Sum,218.0,148.0,187.0,208.0,278.0,188.0,266.0,186.0,NaN,NaN
Column_Average,43.6,29.6,37.4,41.6,55.6,37.6,53.2,37.2,NaN,NaN

In [68]:
df_final.to_csv('update_dataset1.csv', index=True)
print("File 'dataset1.csv' has been updated as 'update_dataset1.csv'")

File 'dataset1.csv' has been updated as 'update_dataset1.csv'

In [69]:
ls

dataset1.csv  update_dataset1.csv  W1Act5.ipynb

In [70]:
from google.colab import files
files.download('update_dataset1.csv')

In [71]:
df_final.index.name = "Rows/Columns"
df_final.to_csv('update_dataset1.csv', index=True)